### ISSUE TITLE
Implement all CSS3 selectors

### ISSUE THREAD

**Issue by curvedmark** [curvedmark/roole#1]
- `:nth-child()`
- `:not()`
- optionally selector namespace

**Comment by jamiebuilds** [comment]
Is the only problem that it doesn't accept parenthesis? This is definitely necessary asap

**Comment by Kolatzek** [comment]
Workarround for ...child() and so on is simple: use it as string

$tmp = "nth-last-child(2)"
.wp-paginate li:$tmp a.page:after
  content: ' '

**Comment by curvedmark** [comment]
Note that this is a hack, although the output CSS is correctly, the selector won't be extended correctly unless the selector used in `@extend` is also hacked that way.

**Comment by tomturton** [comment]
Roole is looking very promising, but this needs to be supported as a priority.

**Comment by curvedmark** [comment]
Just curious, do you guys actually use selector namespace? I'm thinking of delaying it.

**Comment by curvedmark** [comment]
Implement in 3ac50b577b853d6b4c7c8540c6cd154e5cf661f4.

selector namespace is not implement, closing this one and create new one specifically for selector namespace.
