### ISSUE TITLE
Allow to use variables in @import

### ISSUE THREAD

**Issue by mishanga** [curvedmark/roole#102]
```
$theme = normal;
@import 'theme_${normal}';
```

Now it looks like:

```
@if $theme is normal {
    @import 'theme_normal';
}
```

**Comment by curvedmark** [comment]
It's already implemented in master. Forget to mention it in the changelog. Thanks for the report.

BTW, you need to use double-quote string, which supports interpolation.

**Comment by mishanga** [comment]
Great! Thanks!
