### ISSUE TITLE
Allow to create empty list

### ISSUE THREAD

**Issue by mishanga** [curvedmark/roole#105]
UPD: duplicate of #97 

It's impossible now to create empty list / range.
Hack `1...1` looks ugly.

Concept syntax:

```
$a = []; // empty list
$b = [foo bar]; // filled list
$c = [1..2]; // range
```

**Comment by dfilatov** [comment]
:+1:

**Comment by curvedmark** [comment]
The first two examples are already implemented in the master.

Didn't think of `[1..2]`, will support it soon.

**Comment by mishanga** [comment]
`npm publish`? :)

**Comment by mishanga** [comment]
How to push new element to list?

**Comment by curvedmark** [comment]
After thinking about `[1..2]`, I wonder what the result should be? `[1 2]` or `1..2` contained in a list? In ruby, it's the latter.

In the doc of 0.4, I said ranges are essentially lists. But I want to change that in 0.5.

The reason:

```
$list = a b,c d;
$range = 2..1;
$output = $list[$range];
```

If ranges are always converted to lists automatically, then `$output` is the same as `$list[2 1]`. Lists as member expression are not currently supported, but we can suppose the result list should contain `c` and `b`.

The question is, what the separator should be?

From the range point of view, we are extracting items from index 2 to index 1, so it should be `c,b`.

But from the list point of view, we are extracting items of index 2 and index 1. There is no concept of direction, so when extracting an item, it's logical to also extract the separator after that item. The result is then `c b`.

This kind of contradiction suggests that ranges should not be convert to ranges automatically. So `[1..2]` should not be converted to `[1 2]` or `[[1 2]]` for that matter.

So I will just follow ruby on this one.

> How to push new element to list?

After adding bifs like `$push()`, `$pop()`, etc, I will publish 0.5 on npm.
