### ISSUE TITLE
Bug: SyntaxError: Unexpected ','

### ISSUE THREAD

**Issue by mishanga** [curvedmark/roole#112]
Code:

```
$isIE9 = '(-ms-high-contrast: active), (-ms-high-contrast: none)';
@media screen and $isIE9 {
    a { color: red }
}
```

Run:

``` bash
mishanga@mishaga-osx:~/roole > ./node_modules/.bin/roole media.roo
/Users/mishanga/roole/media.roo:3:19

SyntaxError: Unexpected ','

    1| $isIE9 = '(-ms-high-contrast: active), (-ms-high-contrast: none)';
    2|
    3| @media screen and $isIE9 {
    ---------------------^
    4|     a { color: red }
    5| }
    6|
```

**Comment by curvedmark** [comment]
Yeah, interpolating media query list and selector list are not currently supported, due to the complexity of flattening them and the seemingly lacking of good use case.

I can see in this case you are trying to target ie9. How about use conditional comments instead?

**Comment by mishanga** [comment]
Yep, I'll use conditional comments.
Is there a way to escape commas?

**Comment by curvedmark** [comment]
I think not, the media query string is always parsed by the parser as a media query.

I will leave this issue open until a more user friendly error will be thrown. I agree the current one is confusing.

**Comment by curvedmark** [comment]
Fixed in master
