### ISSUE TITLE
Update roole.org with latest changelog and docs

### ISSUE THREAD

**Issue by arikon** [curvedmark/roole#117]
Info on http://roole.org is obsolete for now. Newcomers would think that `roole` is not being developed since March, 2013.

**Comment by curvedmark** [comment]
I'm rewriting the website from scratch. Should release it in a week or two. Thanks for caring. :)

**Comment by curvedmark** [comment]
The new website is released. :)

**Comment by arikon** [comment]
@curvedmark Thanks a lot!
