### ISSUE TITLE
Allow placeholder extends

### ISSUE THREAD

**Issue by lunelson** [curvedmark/roole#30]
placeholder or "@extend-only" selectors, which can chain and pass through to one another, are one of the most powerful new features in Sass 3.2. They are the most efficient way to use presentational frameworks and a must for CSS pre-processors going forward... would love to see them here.

**Comment by curvedmark** [comment]
If the goal is to discard the selector being extended, `@void` can be used for this.

If the goal is to replace a class selector or an id class selector, which is part of a bigger selector, with another one, could I ask what's the use case for it?

**Comment by lunelson** [comment]
Ah, interesting. I hadn't seen the `@void` command. Read through it too fast. Very interesting! 
So far as I can see the `@extend` rules are working the way I expect them to, I was checking code such as the following:

```
@void
    .button
        margin: 10px
    .button-lg
        @extend .button
        height: 50px
    .button-sm
        @extend .button
        height: 25px
    .grid-3-4
        width: 75%
    .grid-9-12
        @extend .grid-3-4
```

and got the expected results
