### ISSUE TITLE
Fix installation of npm package in Windows

### ISSUE THREAD

**Issue by denkwai** [curvedmark/roole#35]
I think, there is all needed information on screenshot.
![2013-02-08_2302](https://f.cloud.github.com/assets/1151761/140908/ecd0597e-7232-11e2-8045-265693e92d76.png)

**Comment by curvedmark** [comment]
Oh, man, Windows.

Don't really want to give up Makefile.

Looks like I have to commit the generated parser.

Or include the generated parser in the published package.

**Comment by curvedmark** [comment]
Fixed in 927e00510ecd0b163ef4af48be8e029de0d3c56b

Tested in my virtual machine.

Let me know if it works on your machine.

**Comment by denkwai** [comment]
Everything is ok now, thanks.
