### ISSUE TITLE
Add the all pseudoclass

### ISSUE THREAD

**Issue by keyten** [curvedmark/roole#37]
For example:
a:all(:hover, :active, img &)
->
a:hover, a:active, img a

**Comment by curvedmark** [comment]
Is `:all()` a w3c spec?

This is a nice feature, but I find its use case pretty limited:
- when would you want to give `a:hover`, and `img a` the same styles?
- if you really want them to have the same styles, why not just use `a`?
- the syntax forces users to specify selectors in a single line

But I might have neglected its potential benefits, let me know if that's the case.

**Comment by curvedmark** [comment]
Closed for now, as not hearing from the OP.
