### ISSUE TITLE
*.roo imports fail

### ISSUE THREAD

**Issue by aebsr** [curvedmark/roole#45]
vars.roo

``` css
$background = #000
```

style.roo

``` css
@import 'vars.roo'

body
  background: $background
```

when compiled results in 

> TypeError: Cannot read property 'vars.roo' of undefined
>    at roole.compile.callback (/usr/local/lib/node_modules/roole/lib/roole.js:35:29)
>    at roole.compile (/usr/local/lib/node_modules/roole/lib/roole.js:55:12)
>    at Importer.visitImport (/usr/local/lib/node_modules/roole/lib/importer/importer.js:99:11)
>    at fs.readFile (fs.js:176:14)
>    at Object.oncomplete (fs.js:297:15)

Note this occurs with or without '.roo' added to the imported file name.

**Comment by curvedmark** [comment]
Usually it means the file contains a syntax error.

The misleading error message is a bug that is already fixed in my local repo, which will be published once I finish v0.2.0

But the code you pasted here seems to be valid. Are you sure that's the code generating the error message?

**Comment by aebsr** [comment]
style.roo

``` css
@import url('normalize.css')
@import 'vars'

...
```

vars.roo

``` css
$matte = #fefbfb
$ink = #1a1604
```

The above fails, but the following compiles.

``` css
$matte = #fefbfb
$ink = #1a1604

body
  display: block
```

That's a much better representation of what my code actually look like. To allow me to use imports and continue dev, I've added this extra body rule to the end of the file. 

So to clarify, the the failure to compile only occurs when importing a .roo file with only variables in it.

**Comment by curvedmark** [comment]
I just released v0.2.0, which should give a better error message.

**Comment by curvedmark** [comment]
Before c6a400b73ce8e0ab76a4ed2671753ba78ba28478, trailing outdents are not parse if, for example, assignments are the only rules in the file. I guess that might be the reason.

**Comment by curvedmark** [comment]
Closing as not hearing from the OP.
