### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by jamiebuilds** [curvedmark/roole#46]
## Functions

This should serve as simply a list of functions that could be added, I've italicized the ones that I see as having low use cases. I've made the ones I find important and missing from other preprocessor languages bold.

**String Functions:**
quote, unquote, concat, _split_, _lower-case_, _upper-case_

**Number Functions:**
abs, ceil, floor, min, max, percent, round, _cos_, _log_, _sin_, _tan_, _sqrt_, **random**, **strip**

**List Functions:**
length, nth, concat, **shift**, **unshift**, **push**, **pop**, first, last, **lowest**, **highest**, slice, **contains**, index-of, list-type, **reverse**, sort

**Introspective Functions:**
type-of, unit, _unitless_, comparable
## Color Functions

Color functions are an extremely important part of the preprocessor. Although more complex, they allow the developer to store colors inside of variables without sacrificing the ability to manipulate them.

**Get Color Functions:**
red, green, blue, hue, saturation, lightness, **alpha**

**Set Color Functions:**
red, green, blue, hue, saturation, lightness, alpha, adjust-hue, lighten, darken, saturate, desaturate, fade-in, fade-out, mix, _grayscale_, _complement_, _invert_

> **Note:** the ones with duplicate names could simply have one argument to get the value and a second argument to set the value

**Build/Convert Color Functions:**
hex, rgb, rgba, hsl, hsla

**Misc Color Functions:**
change-color, adjust-color, scale-color

**Comment by curvedmark** [comment]
If you got the time, please also provide some real-world use case for each of these functions in the Functions section.

Note that Roole is not like other CSS preprocessors that rely on these functions to support vendor prefixing. Its ability to manipulate values doesn't have to be that powerful.

So I rely on actually real-world use cases to decide if they should be implemented or not.

**Comment by jamiebuilds** [comment]
When I use Sass I almost always use Compass or Bourbon, both cover (almost) all of the venodor prefixing. However, Compass and Bourbon Neat have a lot more to them.

If you browse through a little you'll quickly find stuff that I'm talking about, like Compass's Vertical Rhythm functions/mixins that allow you to maintain a baseline grid easier. You can also see stuff like grid systems, frameworks, etc. that heavily use mixins/functions to have better maintenance.

All of these require some amount of built in functions that allow them to manipulate things easily. You'd be amazed how much can be built with just a few functions.

As for providing use cases, I don't have the time right now (it's 12am in Boston), but I could provide you with some of them if you need me too.

I'd hope that you'd at least try to match the functionality of other preprocessors, otherwise this will always feel like a half-baked processor to developers.

Even some of these which aren't in other languages I've actually built for myself using complex functions (which I'm building [a collection of](https://github.com/thejameskyle/sassier) on Github)

**Comment by curvedmark** [comment]
Should also implement color blending functions.

Maybe steal code from heygrady/scss-blend-modes

**Comment by jamiebuilds** [comment]
I believe I've seen a javascript library for calculating photoshop-like blend modes, although I can't find it now.

**Comment by iamcarrico** [comment]
Question: I think there are two kinds of functions, ones that are easy to add to the $bif var, and ones that are easier not to add into it. And would probably be easier to just add as a .roo file. Is that possible? 

Here is an example:

```
$percentage = @function $number {
  @return $unit($number * 100, '%');
};
```

Also: if we add in a .roo file that gets added by default, can we also add in a standard set of variables along with it? 
Example: $legacy-support-for-ie8, so that we can make functions/mixins that will return different css for different legacy needs.

**Comment by curvedmark** [comment]
hmm, I guess we can just write these types of bifs in a .roo file, and manually compile them into js files. I will write an example file soon.

The `$percentage` function, could you provide a use case where it could be useful?

As for variables, I think built-in function should be general enough that they shouldn't be dealing with browser inconsistencies. What is you original need for them?

**Comment by iamcarrico** [comment]
The $percentage function is simple connivence function. 

```
$total_width = 40em;
$column_width = 5em;

.column {
  width: $percentage($column_width / $total_width);
}
```

The need for those variables:

I can create a general mixin for clearfix.

```
$clearfix = @function {

  &:before,
  &:after {
    content: " "; 
    display: table; 
  }

  &:after {
    clear: both;
  }

  @if $legacy-support-for-ie6 or $legacy-support-for-ie7 {
    *zoom: 1;
  }

}
```

This will create standard variables that we can all use when creating functions like those above when extending. Really, this is mainly to establish a standard now so that we don't have many standards popping up in the future.

**Comment by iamcarrico** [comment]
On a related note: I can be found on the IRC at all times if you wanna talk about it.

**Comment by curvedmark** [comment]
functions like `$clearfix()` that deal with actual styling belong to a library.

I don't oppose to something like a standard library that provides these kinds of utility functions.

**Comment by iamcarrico** [comment]
I don't disagree the functions should be in a library or extension. But we should set a standard set of variables for extensions and libraries to utilize. 

Again, refer back to the $legacy-support-for-ie6 variable. The $clearfix function will use this variable... But the variable itself should be standardized

**Comment by curvedmark** [comment]
names are very hard to standardize without enough code to provide an insight. so you can use whatever you want for the moment, and with enough code we can codify them.

but i have a rough idea. we can use something short like $support-ie, which can be either a number or a range, and it can be compared with other numbers or ranges using an operator like `in`

```
$support-ie = 6
@if $support-ie in 6..7 {}

$support-ie = 6..8
@if 6 in $support-ie {}
```

**Comment by jamiebuilds** [comment]
I can't imagine there would need to be a range. eg.: If someone is supporting IE 6 then they are probably every IE above that version.

**Comment by iamcarrico** [comment]
$legacy-support-for-ie6 is what Compass / Sass uses. I agree with @thejameskyle that ranges would be useless here, although I dont disagree with the thought of:

```
 $support-ie = 6;
@if $support-ie >=7 { }
```

If you rather / if it would be easier... once you have figured out the best way to extend the code.... I can make a single extension that just has these common variables and we can play with them there.

**Comment by curvedmark** [comment]
ok. just use any name you see fit. we can refactor them later if necessary.

**Comment by jamiebuilds** [comment]
Closing this as part of cleaning out old issues. Feel free to reopen.
