### ISSUE TITLE
@font-face

### ISSUE THREAD

**Issue by Kolatzek** [curvedmark/roole#57]
"SyntaxError: Unexpected 'f'"

in code like:

 @font-face
   font-family: 'LinuxLibertineOC'
   font-weight: normal
   src: local('Linux Libertine C'), url('font/LinLibertineC_Re-4.0.3.ttf') format("truetype")

What is the solution? I can't find it.

**Comment by curvedmark** [comment]
Implemented in b5d2709fd634ac571a5f390bb46862e2cfa80e84, if you need to use it right now, install this repo as a node module.
