### ISSUE TITLE
Bug with @charset

### ISSUE THREAD

**Issue by Anderson-Juhasc** [curvedmark/roole#61]
I was trying to use the @charset and received this error:

/usr/lib/node_modules/roole/bin/roole:116
            throw error
                  ^
SyntaxError: Unexpected 'c'

  (style.roo 1:2)
  1| @charset "UTF-8";
  ----^
  2|

**Comment by curvedmark** [comment]
It's not implemented yet. I'll add it in v0.3.0

**Comment by curvedmark** [comment]
Fixed in f2a15e0cd3dbe7e0c10eddae7f440fa4b17a6b41

**Comment by Anderson-Juhasc** [comment]
Thanks.
