### ISSUE TITLE
Implement @extend-all

### ISSUE THREAD

**Issue by curvedmark** [curvedmark/roole#63]
```
.button {
    display: inline-block;
}

.button.active {
    border: 1px solid;
}

.button.active .icon {
    float: left;
}

#submit {
    @extend-all .button;
}
```

->

```
.button,
#submit {
    display: inline-block;
}

.button.active,
#submit.active {
    border: 1px solid;
}

.button.active .icon,
#submit.active .icon, {
    float: left;
}
```

This is an experimental feature, feel free to leave any ideas and suggestions.

**Comment by curvedmark** [comment]
Landed in 685264d460c190e6674a88c74f48cfc76cfa954f

**Comment by stef-rausch** [comment]
:+1:

**Comment by curvedmark** [comment]
@StefanoRausch, thank you for your appreciation, but please don't +1 that many resolved issues. It generates a lot of messages, yet it doesn't bring much useful information. You can show you appreciation by telling more people about it. :)
