### ISSUE TITLE
How to Use?

### ISSUE THREAD

**Issue by ckizer** [curvedmark/roole#68]
Is there anywhere I can see documentation for how you would use it? I guess I'm a bit confused. Is this a sass or Stylus replacement? The live editor showed me CSS on both sides of the window. Is this a syntax checker? What is an example use case?

Thanks!

**Comment by curvedmark** [comment]
Yes, it's meant to compete with Sass/Stylus. If you scroll down the website, there are plenty code snippets to show you how to use Roole, or are you looking for something else?

I will update the live editor to make the default code contain some Roole specific constructs.
