### ISSUE TITLE
Error when trying to compile css.roo

### ISSUE THREAD

**Issue by ammartins** [curvedmark/roole#70]
/usr/lib/node_modules/roole/bin/roole:139
      throw error
            ^
SyntaxError: Unexpected ' '

  (css/css.roo 2:10)
  1| body
  2|   margin: 0

For some reason every-time I try to run it I get an error on the roole file itself.

**Comment by curvedmark** [comment]
What version did you use? After 0.3.0, roole is a superset of CSS.

**Comment by ammartins** [comment]
Hi,

roole -v
0.3.1,

Thanks, changed the syntax working like a charm.
