### ISSUE TITLE
Functions within Mixins

### ISSUE THREAD

**Issue by iamcarrico** [curvedmark/roole#79]
A function cannot be called within a mixin.

I created a test to show what I mean in the PR #78.

(side note: Why no more coffee script?)

**Comment by curvedmark** [comment]
Thanks for the report, fixed in 2a153e885e725c06a3f9a02c8cb6c140a5c7c0b1

As for coffee script, just experimenting with vanilla js, probably will revert back when it becomes repulsive enough, haha.

**Comment by iamcarrico** [comment]
Whew! Good to know ;-)
