### ISSUE TITLE
Local Browser tests all fail

### ISSUE THREAD

**Issue by iamcarrico** [curvedmark/roole#81]
I get this error: Uncaught TypeError: Cannot set property 'len' of undefined 

This is because the line:  `var bif = {};` is called after the functions are added to that variable. Not sure how to fix it, or if you get the same compile issue. It does NOT affect the command line tests.

**Comment by curvedmark** [comment]
Thanks, fixed in 6570a7db9a3b7aee4566ecedfa8cc21729be55cb
