### ISSUE TITLE
Revert test units back to coffescript

### ISSUE THREAD

**Issue by curvedmark** [curvedmark/roole#85]
i regret. embedding css in vanilla js is a nightmare.

**Comment by iamcarrico** [comment]
Well, I could've told yah that. :-P 

If you want, you can assign this to me and I will finish it off.

**Comment by curvedmark** [comment]
yes, please. :heart: 

most tests should be directly revertable.

**Comment by iamcarrico** [comment]
This issue is resolved within #86.

**Comment by curvedmark** [comment]
thanks, merged.
