### ISSUE TITLE
Bower Package

### ISSUE THREAD

**Issue by chrisui** [curvedmark/roole#88]
What are your thoughts on making Roole available through [Bower](http://bower.io/)?

It would require an extra bower.json file to be added to the root as defined [here](https://github.com/twitter/bower#defining-a-package). Would be as simple as the json:

```
{
  "name": "roole",
  "version": "0.1.0",
  "main": "dist/roole.min.js"
}
```

and then it would just need to be registered with bower. Would be really nice to be able to define roole as a dependency when I'm using bower in my projects.

Also, although it is probably a seperate issue and for a different discussion, but if we were to have Roole as a package would it make sense to have a compiled js file kept in the dist folder. So you can simply define Roole as a dependency in your project and point to the distributed file. Nice workflow imo.

**Comment by curvedmark** [comment]
Since I use semver tags, would simply committing `dist/roole.min.js` make roole bower-compatible?

**Comment by chrisui** [comment]
I think this would've been the case until now. They've changed to be stricter on people registering packages so now it is required to have a valid package manifest. See [this issue](https://github.com/twitter/bower/issues/366).

**Comment by curvedmark** [comment]
But you can always use something like this in your `bower.json` file:

```
"dependencies": {
    "roole": "https://github.com/curvedmark/roole.git#v0.4.x"
}
```

And it would be exactly the same, right?

**Comment by chrisui** [comment]
This does indeed work. Their documentation is a bit misleading trying to be strict and say you _must_ do this but yet provide a workaround.

I can see there isn't much benefit you setting up Roole as a package and registering it. Would still be nice maybe to distribute the compiled js file in the repository for the purpose of easily being able to consume Roole as a dependency. A non-minified and minified version would be nice.

**Comment by curvedmark** [comment]
ad86781667c61adbfaa39c3f84f45899efba57e4
