### ISSUE TITLE
Variable Variables

### ISSUE THREAD

**Issue by chrisui** [curvedmark/roole#90]
Would be nice to have these.

``` css
$red = #ff0000;
$green = #00ff00;
$theme = red; (or as string "red")

body {
  background: $$theme;
}
```

**Comment by curvedmark** [comment]
How about just use

```
@import 'vars';
body {
    background: $main-background;
}
```

and having a set of `vars` files which contain different themes, and I will add support for variables within importing urls in 0.5.0 so you can do something like

```
$color = red;
@import "vars-$color";
```

**Comment by chrisui** [comment]
That would work for the simple example I provided but themes is not the issue I am trying to solve. We do however implement themes using the method you suggested. :)

I will try and explain the problem I am trying to solve.

I am putting together a base set of styles for a largedesktop application, where the front end is html/css/js. The idea of these base styles is to be able to rapidly put together interfaces using the components we define in the core styles with minimal custom styling required.

For example for a load of buttons in HTML:

``` html
<a href="#" class="button large">Button</a>
<a href="#" class="button style-2 large">Button</a>
<a href="#" class="button style-3 large">Button</a>
<a href="#" class="button style-4 large">Button</a>
<a href="#" class="button style-positive large">Button</a>
<a href="#" class="button style-negative large">Button</a>
<a href="#" class="button style-warning large">Button</a>
<a href="#" class="button style-action large">Button</a>
```

In a roole stylesheet somewhere I am currently defining a load of styles through variables. You can see the values used here will also be able to be used for styling content blocks, notifications etc. (basically any component you can think of will be able to use these styles)

``` css
$style-action-background-colour                 ?= #169df0;
$style-action-border-colour                     ?= #1188d2;
$style-action-text-colour                       ?= #ffffff;
$style-action-highlight-background-colour       ?= #0f8cd9;
$style-action-highlight-border-colour           ?= #085c90;

$style-negative-background-colour               ?= #f01f08;
$style-negative-border-colour                   ?= #d11b07;
$style-negative-text-colour                     ?= #ffffff;
$style-negative-highlight-background-colour     ?= #e01d07;
$style-negative-highlight-border-colour         ?= #9a1203;

// Etc etc.
```

So then elsewhere, where we define the button styles, we currently have to have something along the lines of the following:

``` css
.button {
    &.style-negative {
        @mixin $button-styles($style-negative-background-colour, $style-negative-text-colour, $style-negative-border-colour, $style-negative-highlight-background-colour, $style-negative-highlight-border-colour);
    }

    &.style-action {
        @mixin $button-styles($style-action-background-colour, $style-action-text-colour, $style-action-border-colour, $style-action-highlight-background-colour, $style-action-highlight-border-colour);
    }

    /// Etc etc.
}
```

This achieves what we want but isn't very flexible. For me it looks a bit messy and seems like too much repeated code. Also, everytime we wanted to add/remove a style block (although this is very rare) we'd have to add/remove code across all components using them.

My idea was that we would be able to define a list of 'supported styles' in the variable stylesheet. Then wherever we use them we simple iterate over that list.

``` css
@for $style-name in $supported-styles {
   /// We'd implement a function to easily get a style value given the style name and value we are looking for. (this would be where we'd use variable variables)
   $bg = $get-style-value($style-name, 'background-colour')
   // ...
   @mixin $button-styles($bg, ...)
}
// this could all be wrapped up into another function as well to simplify further
```

I hope this explains our use case a bit better. This is the same problem I'm trying to solve (well an implementation I'm keen to improve) as when I was interested in getting full [member expression support](https://github.com/curvedmark/roole/issues/71)

**Comment by curvedmark** [comment]
you can make `$button-styles` use global variables instead

``` css
.button {
    &.style-negative {
        @import 'vars-negative';
        @mixin $button-styles();
    }

    &.style-action {
        @import 'vars-action';
        @mixin $button-styles();
    }
}
```

``` css
$button-styles = @function {
    background: $background-colour;
    color: $text-colour;
    // etc
}
```

``` css
// vars-negative

$background-colour                 ?= #169df0;
$border-colour                     ?= #1188d2;
$text-colour                       ?= #ffffff;
$highlight-background-colour       ?= #0f8cd9;
$highlight-border-colour           ?= #085c90;
```

``` css
// vars-action

$background-colour               ?= #f01f08;
$border-colour                   ?= #d11b07;
$text-colour                     ?= #ffffff;
$highlight-background-colour     ?= #e01d07;
$highlight-border-colour         ?= #9a1203;
```

will it work for you?

**Comment by chrisui** [comment]
This would work however it isn't ideal due to the number of files we'd end up with. Taking into consideration each theme would have to have a copy of all these files with their own variable definitions and users can create custom themes. This currently simply requires the user to provide a custom Roole file where they can override any of the style definitions. With the 'file for each block' approach everything would be too separated (plus we'd need the functionality to have variables in import strings as you have mentioned)

Is there a reason you would rather not have variable variables implemented into Roole?

**Comment by curvedmark** [comment]
Variable variables tend to be confusing. Code can quickly be hard to understand just by using a few of them.

**Comment by chrisui** [comment]
I totally agree it isn't something I like to use.

Just trying to solve a problem where we don't have some key/value map or proper member expression support which would be the ideal solutions and powerful features for a language such as Roole. Feel free to close this issue though as it isn't the ideal feature for now.

Thanks for your work and support btw!
