### ISSUE TITLE
Disable calculation in calc

### ISSUE THREAD

**Issue by SalomonBrys** [curvedmark/roole#93]
There is a problem with the CSS3 calc function.

Because Roole interpolates arithmetic operations, when I use the rule:
left: calc(50% - 50px)

It is translated to the browser as:
left: calc(0%)

Because 50% - 50px is interpreted by roole whereas it should be interpreted by the browser

**Comment by curvedmark** [comment]
I will fix this once I'm done rewriting visitors. Thanks for the report.

**Comment by mykhailo-ivankiv** [comment]
Does anyone have any ideas how to do it now? Maybe some workarounds?

**Comment by curvedmark** [comment]
Fixed in master
