### ISSUE TITLE
Roole only compiles once

### ISSUE THREAD

**Issue by tomturton** [curvedmark/roole#94]
When using the Roole NPM package in watch mode, only the first compile affects the output CSS file, even though the compile message is output in the terminal.

Command used: roole -w css/styles.roo
Specs: Mac OS X 10.7.5, Roole v0.4.1

**Comment by curvedmark** [comment]
It's fixed in master

**Comment by tomturton** [comment]
Thanks, how do I use master branch with Node?

**Comment by curvedmark** [comment]
Just install this repo with npm

```
npm install curvedmark/roole
```
