### ISSUE TITLE
`@import` supports `.roole` extensions as well as `.roo`

### ISSUE THREAD

**Issue by mxcl** [curvedmark/roole#98]
I would prefer to name my files with a `.roole` extension since this way anyone new to my projects who is not familiar with _Roole_ (it is new after all) will then have the complete name available for them to Google for.

Will provide PR if you point me at the files I will need to edit.

**Comment by curvedmark** [comment]
You can name the containing folder to `roole`, or simply adding a comment in the generated CSS file (I will probably add this feature in the future), or even include a readme file, if you are worried that users might not be familiar with roole.

Allowing two extension names just for the sake of ease of googling is not worth the trouble. I doubt people use .python or .ruby as extension names at the inception of the languages.

But [here is the relevant line](https://github.com/curvedmark/roole/blob/6213fe7c22b9826f047535164ce2ec2a8209cafc/lib/evaluator/node/import.js#L18) anyway if you are interested.

PS. Are you the author of homebrew? I'm a big fan. Use it everyday. I'm thrilled that you are checking roole out. :)

**Comment by mxcl** [comment]
Yes, fair point, and agreed, having two extensions is not sensible.

And yes, Homebrew is mine, glad we have projects that we both find useful from each other! :)
